<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
    <div class="col-xs-12">
        <strong class="heading-title">
            <?php echo __('Related Posts') ?>
        </strong>
    </div>

    <div class="row text-left">
        <?php foreach ($_postCollection as $_post) {
            $featuredImage = $_post->getFeaturedImage();
        ?>
            <div class="col-md-4 col-sm-6">
                <div class="blog-wrapper">
                    <div class="blog-thumb">
                        <a class="thumb rec-fill full-cover"
                           href="<?php echo $_post->getPostUrl() ?>"
                           style="background-image: url(<?php echo(!empty($featuredImage)
                               ? $featuredImage : ''); ?>);">

                            <img class="img-semantic"
                                 src="<?php echo(!empty($featuredImage) ? $featuredImage
                                     : ''); ?>"
                                 alt="<?php echo $_post->getTitle(); ?>"/>
                        </a>
                    </div>

                    <h1 class="blog-heading heading-md under-sep">
                        <a href="<?php echo $_post->getPostUrl() ?>"><?php echo $_post->getTitle(); ?></a>
                    </h1>

                    <div class="blog-desc">
                        <p>
                            <?php echo strip_tags($_post->getShortFilteredContent()) . '...'; ?>
                            <a class="readmore" href="<?php echo $_post->getPostUrl() ?>"
                               title="<?php echo $_post->getTitle() ?>">
                                <?php echo __('Read more') ?>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <?php } ?>
<?php } ?>