<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div>
    <div class="modal-dialog" role="document">
        <div class="">
            <div class="modal-body signin-modal">
                <h3 class="heading-title nm"><?php /* @escapeNotVerified */ echo __('sign in') ?></h3>

                <div class="signin-form">
                    <div class="row">
                        <div class="col-xs-12">
                            <form class="form form-login"
                                  action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                                  method="post"
                                  id="login-form"
                                  data-mage-init='{"validation":{}}'>
                                <?php echo $block->getBlockHtml('formkey'); ?>
                                <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                                    <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
                                    <div class="field email required">
                                        <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                                        <div class="control">
                                            <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form-control" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                                        </div>
                                    </div>
                                    <div class="field password required">
                                        <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                                        <div class="control">
                                            <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="form-control" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
                                        </div>
                                    </div>
                                    <?php echo $block->getChildHtml('form_additional_info'); ?>
                                    <div class="form-action">
                                        <button type="submit" class="btn btn-md btn-full btn-primary" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></button>
                                    </div>
                                    <a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span></a>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="signin-another">
                    <div class="row oe-row-sm-gap">
                        <?php echo $block->getChildHtml('form.social.login.info'); ?>
                        <div class="col-xs-12 oe-col"><span class="sa-signup-suggest">Bạn chưa có tài khoản?<a href="create">Đăng ký</a></span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
