<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>
<?php echo $block->getChildHtml('form_fields_before')?>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.register.extra')?>
<div class="signup-page spacing">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-push-6">
                <div class="signup-form">
                    <h2 class="heading-title nm">Đăng ký</h2>
                    <div class="sform-wrapper">
                        <div class="signin-form">
                            <div class="row">
                                <div class="col-xs-12">
                                    <form class="form create account form-create-account with-border" action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
                                        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
                                        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">
                                        <input name="form_type" type="hidden" value="create_customer">
                                        <input name="utf8" type="hidden" value="✓">
                                        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>


                                        <div class="form-group">
                                            <label for="email_address" class="label"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                                            <div class="control">
                                                <input type="email" name="email" id="email_address" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" class="input-normal input-bordered" data-validate="{required:true, 'validate-email':true}">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="field password required" data-mage-init='{"passwordStrengthIndicator": {}}'>
                                                <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                                                <div class="control">
                                                    <input type="password" name="password" id="password"
                                                           title="<?php /* @escapeNotVerified */ echo __('Password') ?>"
                                                           class="input-normal input-bordered"
                                                           data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                                                           data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                                                           data-validate="{required:true, 'validate-customer-password':true}"
                                                           autocomplete="off">
                                                    <div id="password-strength-meter-container" data-role="password-strength-meter" >
                                                        <div id="password-strength-meter" class="password-strength-meter">
                                                            <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                                                            <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
								<?php /* @escapeNotVerified */ echo __('No Password'); ?>
							</span>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="field confirmation required">
                                                <label for="password-confirmation" class="label"><span><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></span></label>
                                                <div class="control">
                                                    <input type="password" name="password_confirmation" title="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" id="password-confirmation" class="input-normal input-bordered" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                                                </div>
                                            </div>
                                        </div>
                                        <?php echo $block->getChildHtml('form_additional_info'); ?>

                                        <div class="form-group">
                                            <?php if ($block->isNewsletterEnabled()): ?>
                                                <div class="field choice newsletter">
                                                    <input type="checkbox" name="is_subscribed" title="<?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                                                    <label for="is_subscribed" class="label"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Newsletter') ?></span></label>
                                                </div>
                                                <?php /* Extensions placeholder */ ?>
                                                <?php echo $block->getChildHtml('customer.form.register.newsletter')?>
                                            <?php endif ?>

                                            <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                                            <?php if ($_dob->isEnabled()): ?>
                                                <?php echo $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                                            <?php endif ?>

                                            <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
                                            <?php if ($_taxvat->isEnabled()): ?>
                                                <?php echo $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                                            <?php endif ?>

                                            <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
                                            <?php if ($_gender->isEnabled()): ?>
                                                <?php echo $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                                            <?php endif ?>
                                        </div>
                                        <?php if ($block->getShowAddressFields()): ?>
                                        <div class="row">
                                            <div class="field company">
                                                <label for="company" class="label"><span><?php /* @escapeNotVerified */ echo __('Company') ?></span></label>
                                                <div class="control">
                                                    <input type="text" name="company" id="company" value="<?php echo $block->escapeHtml($block->getFormData()->getCompany()) ?>" title="<?php /* @escapeNotVerified */ echo __('Company') ?>" class="form-control <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
                                                </div>
                                            </div>
                                            <div class="field telephone">
                                                <label for="telephone" class="label"><span><?php /* @escapeNotVerified */ echo __('Phone Number') ?></span></label>
                                                <div class="control">
                                                    <input type="text" name="telephone" id="telephone" value="<?php echo $block->escapeHtml($block->getFormData()->getTelephone()) ?>" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" class="form-control <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>">
                                                </div>
                                            </div>

                                            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

                                            <div class="field street required">
                                                <label for="street_1" class="label"><span><?php /* @escapeNotVerified */ echo __('Street Address') ?></span></label>
                                                <div class="control">
                                                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreet(0)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address') ?>" id="street_1" class="form-control <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                                    <div class="nested">
                                                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                                            <div class="additional">
                                                                <label class="label" for="street_<?php /* @escapeNotVerified */ echo $_i ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Address') ?></span>
                                                                </label>
                                                                <div class="control">
                                                                    <input type="text" name="street[]" value="<?php echo $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?php /* @escapeNotVerified */ echo __('Street Address %1', $_i) ?>" id="street_<?php /* @escapeNotVerified */ echo $_i ?>" class="form-control <?php /* @escapeNotVerified */ echo $_streetValidationClass ?>">
                                                                </div>
                                                            </div>
                                                        <?php endfor; ?>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="field required">
                                                <label for="city" class="label"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
                                                <div class="control">
                                                    <input type="text" name="city" value="<?php echo $block->escapeHtml($block->getFormData()->getCity()) ?>" title="<?php /* @escapeNotVerified */ echo __('City') ?>" class="form-control <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
                                                </div>
                                            </div>

                                            <div class="field region required">
                                                <label for="region_id" class="label"><span><?php /* @escapeNotVerified */ echo __('State/Province') ?></span></label>
                                                <div class="control">
                                                    <select id="region_id" name="region_id" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="form-control validate-select" style="display:none;">
                                                        <option value=""><?php /* @escapeNotVerified */ echo __('Please select a region, state or province.') ?></option>
                                                    </select>
                                                    <input type="text" id="region" name="region" value="<?php echo $block->escapeHtml($block->getRegion()) ?>" title="<?php /* @escapeNotVerified */ echo __('State/Province') ?>" class="form-control <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>" style="display:none;">
                                                </div>
                                            </div>

                                            <div class="field zip required">
                                                <label for="zip" class="label"><span><?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?></span></label>
                                                <div class="control">
                                                    <input type="text" name="postcode" value="<?php echo $block->escapeHtml($block->getFormData()->getPostcode()) ?>" title="<?php /* @escapeNotVerified */ echo __('Zip/Postal Code') ?>" id="zip" class="form-control validate-zip-international <?php /* @escapeNotVerified */ echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
                                                </div>
                                            </div>

                                            <div class="field country required">
                                                <label for="country" class="label"><span><?php /* @escapeNotVerified */ echo __('Country') ?></span></label>
                                                <div class="control">
                                                    <?php echo str_replace('class="', 'class="form-control ', $block->getCountryHtmlSelect()) ?>
                                                </div>
                                            </div>
                                            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
                                            <?php if ($addressAttributes): ?>
                                                <?php $addressAttributes->setEntityType('customer_address'); ?>
                                                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                                                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                                                <?php echo $addressAttributes->setShowContainer(false)->toHtml()?>
                                            <?php endif;?>
                                            <input type="hidden" name="default_billing" value="1">
                                            <input type="hidden" name="default_shipping" value="1">
                                        </div>
                                        <?php endif; ?>
                                        <?php /* @noEscape */ echo $block->getBlockHtml('formkey'); ?>
                                        <div class="form-group nm">
                                            <button class="btn btn-md btn-full btn-primary" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>" type="submit">Tạo tài khoản</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="signin-another">
                            <div class="row oe-row-sm-gap">
                                <?php echo $block->getChildHtml('form.social.login.info'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5 col-md-pull-6">
                <div class="signup-features">
                    <h2 class="sf-heading heading-md under-sep">Sẵn sàng để trở thành thành viên</h2>
                    <div class="features-list">
                        <ul class="list-unstyled">
                            <li>
                                <div class="fl-number">1</div>
                                <div class="fl-content">
                                    <p>Đăng ký nhanh, miễn phí và sẽ luôn như vậy. </p>
                                </div>
                            </li>
                            <li>
                                <div class="fl-number">2</div>
                                <div class="fl-content">
                                    <p>Là người đầu tiên nhận thông báo về sản phẩm mới</p>
                                </div>
                            </li>
                            <li>
                                <div class="fl-number">3</div>
                                <div class="fl-content">
                                    <p>Đặc quyền cho các chương trình ưu đãi tuyệt vời… Và hơn thế nữa</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="feature-thumb"><img class="img-responsive" src="//theme.hstatic.net/1000167342/1000243565/14/reg-img.png?v=1369" height="255" width="440" alt="Become our loyal member to get more fascinating benefits"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?php /* @escapeNotVerified */ echo $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null'; ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?php /* @escapeNotVerified */ echo($block->getConfig('general/region/display_all') ? 'true' : 'false'); ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getRegionJson() ?>,
                "defaultRegion": "<?php /* @escapeNotVerified */ echo $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?php /* @escapeNotVerified */ echo $this->helper('Magento\Directory\Helper\Data')->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>
