<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="prd-attr">
        <div class="prda-details bg-milk">
            <h3 class="prda-title"><?php echo __('Product Details')?></h3>
            <div class="panel-wrapper">
                <ul class="list-unstyled prda-table">
                    <?php foreach ($_additional as $_data): ?>
                        <li class="table-row clearfix">
                            <div class="table-col">
                                <div class="t-label"><?php echo $block->escapeHtml(__($_data['label'])) ?></div>
                            </div>
                            <div class="table-col">
                                <div class="t-value"><?php /* @escapeNotVerified */
                                    echo $_helper->productAttribute(
                                        $_product,
                                        $_data['value'],
                                        $_data['code']
                                    ) ?> </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>
