<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    // $templateType =  \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    $description = false;

    $meigee_helper = $this->helper('\Meigee\Tiffany\Helper\TiffanyGeneral');
    $lightbox_status = $meigee_helper->getCustomThemeOptionCnf('tiffany_lightbox', 'lightbox_status');
    $lightbox_widget_status = $meigee_helper->getCustomThemeOptionCnf('tiffany_lightbox', 'lightbox_home');
    $name_align = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'product_name_aligment');
    $stock_status = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'stock_status');
    $image_hover_status = $meigee_helper->getCustomThemeOptionCnf('tiffany_image_hover', 'image_hover_status');
    $image_hover_effect = $meigee_helper->getCustomThemeOptionCnf('tiffany_image_hover', 'image_hover_type');
    ?>
    <div class="best-seller spacing">
        <?php if ($title):?>
            <h2 class="heading-title"><?php /* @escapeNotVerified */ echo $title; ?></h2>
        <?php else : ?>
            <h2 class="heading-title">Sản phẩm nổi bật</h2>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode .' '. $type; if($image_hover_status){echo $image_hover_effect ? ' hover-scale' : ' hover-simple';} ?>">
                <ol class="product-items row">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item col-sm-3">' : '</li><li class="item col-sm-3">' ?>
                        <div class="product-item-info">
                            <div class="image-wrapper">
                                <?php if($lightbox_status && $lightbox_widget_status){ ?>
                                    <a href="<?php echo $block->getImage($_item, $image)->getImageUrl();  ?>" data-toggle="lightbox" class="lightbox-button" data-footer="<?php echo $block->escapeHtml($_item->getName()); ?>" title="<?php echo __('Lightbox'); ?>">
                                        <i class="ion-ios-search"></i>
                                    </a>
                                <?php } ?>
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?php
                                    $hoverImage = $image_hover_status ? $_item->getHoverImage() : false;
                                    if ($hoverImage)
                                    {
                                        $hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                            ->init($_item, 'hover_image')
                                            ->setImageFile($hoverImage)
                                            ->getUrl();
                                        $productImage = $block->getImage($_item, $image, array('data-hover-image'=>$hoverImageUrl));
                                    }
                                    else
                                    {
                                        $productImage = $block->getImage($_item, $image, array('data-hover-image'=>null));
                                    }
                                    // echo $block->getImage($_item, $image)->toHtml();
                                    echo $productImage->toHtml();
                                    ?>
                                </a>
                                <?php if ($showWishlist || $showCompare): ?>
                                    <div class="add-to-links" data-role="add-to-links">
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                            <a href="#"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                               class="action towishlist" data-action="add-to-wishlist"
                                               title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                <i class="ion-heart"></i>
                                                <span><?php /* @escapeNotVerified */ echo __('to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                            <a href="#" class="action tocompare"
                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                               title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                                <i class="ion-arrow-swap"></i>
                                                <span><?php /* @escapeNotVerified */ echo __('to Compare') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <div class="product-item-details">
                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
                                <?php endif; ?>

                                <h4 class="product-item-name <?php echo $name_align; ?>">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </h4>

                                <?php if($stock_status != 4 && $stock_status != 2) {
                                    if ($_item->getIsSalable()): ?>
                                        <div class="stock available"><?php /* @escapeNotVerified */ echo __('Availability') ?><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                    <?php else: ?>
                                        <div class="stock unavailable"><?php /* @escapeNotVerified */ echo __('Availability') ?><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                    <?php endif;
                                } ?>

                                <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                <?php if ($showCart): ?>
                                    <div class="button-wrapper">
                                        <?php if ($_item->isSaleable()): ?>
                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                <button class="btn btn-default btn-cart action tocart"
                                                        data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php else: ?>
                                                <?php
                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                ?>
                                                <button class="btn btn-default btn-cart"
                                                        data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                        type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            <?php endif; ?>
                                        <?php else: ?>
                                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><?php echo __('Read more') ?></a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>