<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
	$meigee_helper = $this->helper('\Meigee\Tiffany\Helper\TiffanyGeneral');
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        // $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
		$grid_columns = $lightbox_status = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'grid_columns');
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        // $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		$grid_columns = '';
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
	$lightbox_status = $meigee_helper->getCustomThemeOptionCnf('tiffany_lightbox', 'lightbox_status');
	$lightbox_listing_status = $meigee_helper->getCustomThemeOptionCnf('tiffany_lightbox', 'lightbox_listing');
	$product_name = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'product_name');
	$product_price = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'product_price');
	$cart_btn = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'cart_btn');
	$compare_btn = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'compare_btn');
	$wishlist_btn = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'wishlist_btn');
	$name_align = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'product_name_aligment');
	$stock_status = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'stock_status');
	$image_hover_status = $meigee_helper->getCustomThemeOptionCnf('tiffany_image_hover', 'image_hover_status');
	$image_hover_effect = $meigee_helper->getCustomThemeOptionCnf('tiffany_image_hover', 'image_hover_type');
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode .' '. $grid_columns ; if($image_hover_status){echo $image_hover_effect ? ' hover-scale' : ' hover-simple';} ?>">
        <?php $iterator = 1; ?>
        <ol class="products clearfix list items product-items row">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
			
			<?php if($viewMode == 'list') { ?>
				 <?php foreach ($_productCollection as $_product): ?>
					<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
					<div class="product-item-info clearfix" data-container="product-grid">
						<div class="image-wrapper">
                            <?php if($compare_btn || $wishlist_btn){ ?>
                                <div data-role="add-to-links" class="add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $wishlist_btn): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <i class="ion-heart"></i>
                                        </a>
                                    <?php endif; ?>
                                    <?php if($compare_btn){
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                        <a href="#"
                                           class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                            <i class="ion-arrow-swap"></i>
                                            <span><?php echo $block->escapeHtml(__('to Compare')); ?></span>
                                        </a>
                                    <?php } ?>
                                </div>
                            <?php } ?>
							<?php
							$hoverImage = $image_hover_status ? $_product->getHoverImage() : false;
							if ($hoverImage)
							{
								$hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
												  ->init($_product, 'hover_image')
												  ->setImageFile($hoverImage)
												  ->getUrl();
								$productImage = $block->getImage($_product, $image, array('data-hover-image'=>$hoverImageUrl));
							}
							else
							{
								$productImage = $block->getImage($_product, $image, array('data-hover-image'=>null));
							}
					
							if ($pos != null) {
								$position = ' style="left:' . $productImage->getWidth() . 'px;'
									. 'top:' . $productImage->getHeight() . 'px;"';
							}
							if($lightbox_status && $lightbox_listing_status){
							?>
								<a href="<?php echo $productImage->getImageUrl();  ?>" data-toggle="lightbox" class="lightbox-button" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
									<i class="ion-ios-search"></i>
								</a>
							<?php 
							}
							// Product Image ?>
							
							<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<?php echo $productImage->toHtml(); ?>
							</a>

						</div>
						<div class="product details product-item-details">
							<?php if($product_name){
								$_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
								<strong class="product name product-item-name">
									<a class="product-item-link"
									   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
									</a>
								</strong>
							<?php } ?>
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
							<div class="price-availability-block clearfix">
								<?php if($stock_status != 4 && $stock_status != 1) { 
									if ($_product->getIsSalable()): ?>
										<div class="stock available"><?php /* @escapeNotVerified */ echo __('Product') ?> <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><?php /* @escapeNotVerified */ echo __('Product') ?> <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
									<?php endif;
								} ?>
								<?php if($product_price){
									/* @escapeNotVerified */ echo $block->getProductPrice($_product);
								} ?>
							</div>
							<?php echo $block->getProductDetailsHtml($_product); ?>
		
							<div class="product-item-inner">
								 <?php if ($showDescription):?>
									<div class="product description product-item-description">
										<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
										   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
									</div>
								<?php endif; ?>
								<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<?php if($cart_btn){ ?>
										<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
											<?php if ($_product->isSaleable()): ?>
												<?php $postParams = $block->getAddToCartPostParams($_product); ?>
												<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
													<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
													<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
													<?php echo $block->getBlockHtml('formkey')?>
													<button type="submit"
															title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
															class="action tocart btn btn-default btn-cart">
														<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
												</form>
											<?php else: ?>
												<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><?php echo __('Read more') ?></a>
											<?php endif; ?>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
					<?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
				<?php endforeach; ?>
			<?php } else { ?>
				<?php foreach ($_productCollection as $_product): ?>
					<?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
					<div class="product-item-info clearfix" data-container="product-grid">
						<div class="indent">
							<div class="image-wrapper">
                                <?php if($compare_btn || $wishlist_btn){ ?>
                                    <div data-role="add-to-links" class="add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $wishlist_btn): ?>
                                            <a href="#"
                                               class="action towishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <i class="ion-heart"></i>
                                            </a>
                                        <?php endif; ?>
                                        <?php if($compare_btn){
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                            <a href="#"
                                               class="action tocompare"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                               role="button">
                                                <i class="ion-arrow-swap"></i>
                                                <span><?php echo $block->escapeHtml(__('to Compare')); ?></span>
                                            </a>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
								<?php
								$hoverImage = $image_hover_status ? $_product->getHoverImage() : false;
								if ($hoverImage)
								{
									$hoverImageUrl = $this->helper('Magento\Catalog\Helper\Image')
													  ->init($_product, 'hover_image')
													  ->setImageFile($hoverImage)
													  ->getUrl();
									if($_product->getHoverImage()){
										$productImage = $block->getImage($_product, $image, array('data-hover-image'=>$hoverImageUrl));
									}
								}
								else
								{
									$productImage = $block->getImage($_product, $image, array('data-hover-image'=>null));
								}
						
								if ($pos != null) {
									$position = ' style="left:' . $productImage->getWidth() . 'px;'
										. 'top:' . $productImage->getHeight() . 'px;"';
								} ?>
								<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
									<?php echo $productImage->toHtml(); ?>
								</a>
								<?php if($lightbox_status && $lightbox_listing_status){ ?>
									<a href="<?php echo $productImage->getImageUrl();  ?>" data-toggle="lightbox" class="lightbox-button" data-footer="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" title="<?php echo __('Lightbox'); ?>">
										<i class="ion-ios-search"></i>
									</a>
								<?php } ?>

							</div>
							<div class="product details product-item-details">
								<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
								<?php if($product_name){
									$_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
									<h4 class="product name product-item-name <?php // echo $name_align; ?>">
										<a class="product-item-link"
										   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
										</a>
									</h4>
								<?php }
								if($stock_status != 4 && $stock_status != 2) { 
									if ($_product->getIsSalable()): ?>
										<div class="stock available"><?php echo __('Product'); ?> <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><?php echo __('Product'); ?> <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
								   <?php endif; 
								}
								if($product_price){
									/* @escapeNotVerified */ echo $block->getProductPrice($_product);
								}
								echo $block->getProductDetailsHtml($_product); ?>
								<div class="product-item-inner">
									 <?php if ($showDescription):?>
										<div class="product description product-item-description">
											<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
											<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
											   class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
										</div>
									<?php endif; ?>
								</div>
								<?php if($cart_btn){ ?>
									<div class="button-wrapper">
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey')?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart btn btn-default btn-cart">
													<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
												</button>
											</form>
										<?php else: ?>
											<a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php echo __('Read more') ?>" class="btn btn-default"><?php echo __('Read more') ?></a>
										<?php endif; ?>
									</div>
								<?php } ?>
							</div>
						</div>
					</div>
					<?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
				<?php endforeach; ?>
			<?php } ?>
        </ol>
    </div>
	<div class="toolbar-bottom">
		<?php echo $block->getToolbarHtml() ?>
	</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
