<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<section>
    <div class="subscribe-block full-cover">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="subscribe-wrapper">
                        <h2 class="heading-giant has-desc white"><?php echo __('Connect with Precita');?></h2>
                        <p class="sub-desc"><?php /* @escapeNotVerified */ echo __('Sign Up for Precita Newsletter');?></p>
                        <div class="subscribe-box">
                            <div class="subscribe-form clearfix" style="float:none;">
                                <form class="form subscribe"
                                      novalidate
                                      action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
                                      method="post"
                                      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                                      id="newsletter-validate-detail">
                                    <div class="field newsletter">
                                        <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
                                        <div class="control">
                                            <input class="form-control" name="email" type="email" id="newsletter"
                                                   placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                                   data-validate="{required:true, 'validate-email':true}"/>
                                        </div>
                                    </div>
                                    <button class="action subscribe btn btn-primary type-2 primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                                        <i class="ion-email"></i>
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
