<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post info template
 *
 * @var $block \Magefan\Blog\Block\Post\Info
 */
?>

<?php $_post = $block->getPost() ?>

<div class="post-info clear">
    <div class="item post-posed-date">
        <span class="label"><?php echo __('Posted:') ?></span>
        <span class="value"><?php echo $_post->getPublishDate('F d, Y') ?></span>
    </div>
</div>