<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('Account Information') ?></strong></div>
    <div class="block-content row">
        <div class="box box-information col-sm-6">
			<div class="box-inner">
				<strong class="box-title">
					<span><?php /* @escapeNotVerified */ echo __('Contact Information') ?></span>
					<a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/edit') ?>" title="<?php /* @escapeNotVerified */ echo __('Edit') ?>">
						<i class="fa fa-pencil"></i>
					</a>
				</strong>
				<div class="box-content">
					<p>
						<?php echo $block->escapeHtml($block->getName()) ?><br>
						<?php echo $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
					</p>
				</div>
				<div class="box-actions">
					
					<a href="<?php /* @escapeNotVerified */ echo $block->getChangePasswordUrl() ?>" class="action change-password">
						<?php /* @escapeNotVerified */ echo __('Change Password') ?>
					</a>
				</div>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter col-sm-6">
				<div class="box-inner">
					<strong class="box-title">
						<span><?php /* @escapeNotVerified */ echo __('Newsletters') ?></span>
						<a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getUrl('newsletter/manage') ?>" title="<?php /* @escapeNotVerified */ echo __('Edit') ?>"><i class="fa fa-pencil"></i></a>
					</strong>
					<div class="box-content">
						<p>
							<?php if ($block->getIsSubscribed()): ?>
								<?php /* @escapeNotVerified */ echo __('You subscribe to "General Subscription".') ?>
							<?php else: ?>
								<?php /* @escapeNotVerified */ echo __('You don\'t subscribe to our newsletter.') ?>
							<?php endif; ?>
						</p>
						<?php /* Extensions placeholder */ ?>
						<?php echo $block->getChildHtml('customer.account.dashboard.info.extra')?>
					</div>
				</div>
            </div>
        <?php endif; ?>
    </div>
</div>
