<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var $block Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist */
$meigee_helper = $this->helper('\Meigee\Tiffany\Helper\TiffanyGeneral');
$wishlist_btn = $meigee_helper->getCustomThemeOptionCnf('tiffany_product_listing', 'wishlist_btn');
?>
<?php if ($block->getWishlistHelper()->isAllow() && $wishlist_btn): ?>
    <a href="#"
       class="action towishlist"
       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($block->getProduct()); ?>'
       data-action="add-to-wishlist"
       role="button">
        <i class="ion-heart"></i>
        <span><?php /* @escapeNotVerified */ echo __('to Wish List'); ?></span>
    </a>
<?php endif; ?>
