<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
 
?>

<?php if (count($block->getStores())>1):
$label = $this->helper('\Meigee\Tiffany\Helper\TiffanyGeneral')->getCustomThemeOptionCnf('tiffany_lang_switcher', 'lang_switcher_label');
$languages = $this->helper('\Meigee\Tiffany\Helper\TiffanyGeneral')->getCustomThemeOptionCnf('tiffany_lang_switcher', 'lang_switcher_status');
?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="language switcher-language header-switcher" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
	<?php if($label){ ?>
		<strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
	<?php } ?>
	<?php if($languages == 'language_flags'){ ?>
		<div class="actions dropdown options switcher-options">
			<ul class="form-languages">
				 <li class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
					<span><img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($block->getStoreName()); ?>.jpg" alt="<?php echo $block->escapeHtml($block->getStoreName()) ?>"></span>
				</li>
				<?php foreach ($block->getStores() as $_lang): ?>
					<?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
						<li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
							<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
								<img src="<?php echo $block->getViewFileUrl('images').'/lang/'.$block->escapeHtml($_lang->getName()); ?>.jpg" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>">
							</a>
						</li>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</div>
	<?php } else { ?>
		<div class="actions dropdown options switcher-options">
			<div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
				<strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
					<span><?php echo $block->escapeHtml($block->getStoreName()) ?></span>
				</strong>
			</div>
			<ul class="dropdown switcher-dropdown"
				data-mage-init='{"dropdownDialog":{
					"appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
					"triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
					"closeOnMouseLeave": false,
					"triggerClass":"active",
					"parentClass":"active",
					"buttons":null}}'>
				<?php foreach ($block->getStores() as $_lang): ?>
					<?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
						<li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
							<a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
								<?php echo $block->escapeHtml($_lang->getName()) ?></a>
						</li>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</div>
	<?php } ?>
</div>
<?php endif; ?>
